apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJibUZ0Y25WemJHRnVPbWRvY0Y5aVUweFdRVzh6ZGxSRlpYQnZjRkkzY0VreE5FUkJkRzVQWXpoV1YyWXdWWEp6VWxjPSIKCQl9LAoJCSJoYXJib3IuZGVtby5taXJhcG9saXMtdGVhbS5ydSI6IHt9LAoJCSJuZXh1cy5zcC5hZmx0LXN5c3RlbXMucnU6NzQ0MyI6IHt9LAoJCSJuZXh1cy5zcC5hZmx0LXN5c3RlbXMucnU6OTQ0MyI6IHt9Cgl9LAoJImNyZWRzU3RvcmUiOiAiZGVza3RvcCIsCgkiY3VycmVudENvbnRleHQiOiAiZGVza3RvcC1saW51eCIsCgkicGx1Z2lucyI6IHsKCQkiLXgtY2xpLWhpbnRzIjogewoJCQkiZW5hYmxlZCI6ICJ0cnVlIgoJCX0sCgkJImRlYnVnIjogewoJCQkiaG9va3MiOiAiZXhlYyIKCQl9LAoJCSJzY291dCI6IHsKCQkJImhvb2tzIjogInB1bGwsYnVpbGR4IGJ1aWxkIgoJCX0KCX0sCgkiZmVhdHVyZXMiOiB7CgkJImhvb2tzIjogInRydWUiCgl9Cn0=
type: kubernetes.io/dockerconfigjson
